import SessionProviderWrapper from "@/components/providers/session";
import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";

const inter = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
            <body
                className={`${inter.className}  min-h-screen flex flex-col bg-[#fafafa]  `}
            >
                <SessionProviderWrapper>{children}</SessionProviderWrapper>
            </body>
        </html>
    );
}
