import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
            <body
                className={`${inter.className} flex flex-col min-h-screen bg-[#fafafa]  mx-auto`}
            >
                <Toaster />
                <Navbar />
                <main className="flex-grow w-full  max-w-screen-2xl mx-auto  px-4 ">
                    {children}
                </main>
            </body>
        </html>
    );
}
