import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/PublicNavBar/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Toaster />
            <Navbar />
            <main className="flex-grow w-full flex h-full  max-w-screen-lg mx-auto  px-4 ">
                {children}
            </main>
        </>
    );
}
